server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test2020?useUnicode=true&characterEncoding=utf8&userSSL=false&serverTimezone=GMT
    username: root
    password: qq6168058
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#  application:
#    name: anlysis-service
mybatis:
  type-aliases-package: cn.csust.lingyi.pojo
logging:
  level:
    cn.csust.lingyi.mapper: debug
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#  instance:
#    lease-expiration-duration-in-seconds: 15
#    lease-renewal-interval-in-seconds: 5